sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tunstokun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tunstokun/docker-react npm run test