sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tunstokun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tunstokun/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-934427357452"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_acess_key: 
    secure: $AWS_SECRET_KEY
